parameters:
  - name: scenarios
    type: object
    default:
      - agent-bvt
      - extension-telemetry-pipeline

  - name: distros
    type: object
    default:
      - publisher: "RedHat"
        offer: "rhel-sig-publishing-test-preview"
        sku: "9_0"
        version: "latest"
        name: "rhel9Raw"

trigger:
  - develop

# no PR triggers
pr: none

schedules:
  - cron: "0 */8 * * *" # Run every 8 hours
    displayName: Daily validation builds
    branches:
      include:
      - develop
    always: true

variables:
  - template: templates/vars.yml

  - name: SSH_PUBLIC
    value: "$(sshPublicKey)" # set in GUI variables
  - name: rgNamePrefix
    value: "$(rgPrefix)$(Build.BuildId)"


pool: #larohra-dcrvmsspool
  vmImage: ubuntu-latest

stages:
  - stage: "Execute"
    jobs:
      - template: 'templates/setup-vm-and-execute-tests.yml'
        parameters:
          scenarios:
            - ${{ parameters.scenarios }}
          distros:
            - ${{ parameters.distros }}
          rgPrefix: $(rgNamePrefix)

  - stage: "Cleanup"
    condition: succeededOrFailed()
    jobs:
      - job: "Wait"
        pool: server
        # ToDo: Add a parameter to force wait before deleting the Test VMs
        condition: in(stageDependencies.Execute.CreateVM.result, 'Failed', 'SucceededWithIssues')
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 50
            inputs:
              notifyUsers: 'larohra'
              onTimeout: 'resume'

      - template: templates/arm-delete.yml
        parameters:
          scenarios:
            - ${{ parameters.scenarios }}
          distros:
            - ${{ parameters.distros }}
          rgPrefix: $(rgNamePrefix)