# Microsoft Azure Linux Agent
#
# Copyright 2018 Microsoft Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Requires Python 2.6+ and Openssl 1.0+
#

"""
This module monitors kernel events (CPU soft lockups) by parsing dmesg output
and reports them via telemetry. This helps Azure detect and diagnose VM health issues.

CPU soft lockups occur when a CPU is stuck in kernel code for more than the configured
threshold (typically 20+ seconds), indicating potential system issues.
"""

import datetime
import json
import os
import re

import azurelinuxagent.common.conf as conf
import azurelinuxagent.common.logger as logger
from azurelinuxagent.common.event import add_event, WALAEventOperation
from azurelinuxagent.common.future import ustr
from azurelinuxagent.common.utils.shellutil import run_command
from azurelinuxagent.common.version import AGENT_NAME
from azurelinuxagent.ga.periodic_operation import PeriodicOperation


class MonitorKernelSoftLockup(PeriodicOperation):
    """
    Periodic operation to monitor dmesg for CPU soft lockup events.
    
    CPU soft lockup events indicate that a CPU core has been stuck in kernel code 
    for an extended period (typically 20+ seconds).
    
    This class parses dmesg output, aggregates events, and sends 
    summarized telemetry to avoid overwhelming the telemetry pipeline.
    """

    # Regex to detect kernel soft lockup events and extract CPU ID + stuck duration.
    #
    # Matches the message printed by kernel/watchdog.c:
    #   "BUG: soft lockup - CPU#<id> stuck for <seconds>s! [<process>:<pid>]"
    #
    # The prefix before "BUG:" varies by kernel version (e.g., "watchdog:", "NMI watchdog:")
    # but re.search() handles that, no prefix matching needed.
    _SOFT_LOCKUP_PATTERN = re.compile(
        r'BUG:\s*soft lockup\s*-\s*CPU#(\d+)\s+stuck for (\d+)s',
        re.IGNORECASE
    )
    
    # Pattern to extract the kernel monotonic timestamp from a dmesg line.
    #
    # Kernel printk format: "[%5lu.%06lu]" e.g. "[   12.345678]", "[8640000.123456]"
    # Seconds are space-padded, microseconds are zero-padded to 6 digits.
    # Matches raw dmesg output only (not dmesg -T or syslog formats).
    _DMESG_TIMESTAMP_PATTERN = re.compile(
        r'\[\s*(\d+\.\d+)\]'
    )
    
    # File to persist the last processed dmesg timestamp across agent restarts
    _STATE_FILE_NAME = "kernel_soft_lockup_state.json"

    # Path to the kernel boot ID, a unique UUID generated on each boot
    _BOOT_ID_PATH = "/proc/sys/kernel/random/boot_id"

    # Timeout in seconds for dmesg subprocess. 
    _DMESG_TIMEOUT = 60
    _MIN_PERIOD_SECONDS = 300

    def __init__(self):
        period = datetime.timedelta(seconds=max(conf.get_monitor_kernel_soft_lockup_period(), self._MIN_PERIOD_SECONDS))
        super(MonitorKernelSoftLockup, self).__init__(period)
        self._last_processed_timestamp = 0.0
        self._boot_id = self._get_boot_id()
        self._event_aggregates = {}
        self._state_file_path = os.path.join(conf.get_lib_dir(), self._STATE_FILE_NAME)
        self._load_state()
        logger.info("KernelSoftLockup: Initialized - period={0}, watermark={1}, boot_id={2}",
                    period, self._last_processed_timestamp, self._boot_id[:8])

    @staticmethod
    def _get_boot_id():
        """
        Read the current boot ID from /proc/sys/kernel/random/boot_id.
        This is a unique UUID generated by the kernel on each boot.
        Returns empty string on failure (will cause a watermark reset).
        """
        try:
            with open(MonitorKernelSoftLockup._BOOT_ID_PATH, 'r') as f:
                return f.read().strip()
        except Exception as e:
            logger.warn("KernelSoftLockup: Failed to read boot_id: {0}".format(ustr(e)))
            return ""

    def _load_state(self):
        """
        Load persisted state from disk. If boot_id changed (reboot occurred),
        reset the watermark since kernel timestamps restart from 0.
        """
        try:
            if not os.path.exists(self._state_file_path):
                return

            with open(self._state_file_path, 'r') as f:
                state = json.load(f)

            saved_boot_id = state.get("boot_id", "")

            if not saved_boot_id or not self._boot_id:
                logger.info("KernelSoftLockup: Unable to read Boot ID (saved={0}, current={1}). "
                            "Resetting timestamp watermark as a safety measure.".format(
                                ustr(saved_boot_id)[:8], ustr(self._boot_id)[:8]))
                return

            if saved_boot_id != self._boot_id:
                logger.info("KernelSoftLockup: Boot ID changed (saved={0}, current={1}). "
                            "Resetting timestamp watermark due to reboot.".format(
                                ustr(saved_boot_id)[:8], ustr(self._boot_id)[:8]))
                return

            self._last_processed_timestamp = float(state.get("last_timestamp", 0.0))
        except Exception as e:
            logger.warn("KernelSoftLockup: Failed to load state: {0}".format(ustr(e)))
            self._last_processed_timestamp = 0.0

    def _save_state(self):
        """Persist state to disk including boot_id to detect reboots."""
        try:
            state = {
                "last_timestamp": self._last_processed_timestamp,
                "boot_id": self._boot_id
            }
            tmp_path = self._state_file_path + ".tmp"
            with open(tmp_path, 'w') as f:
                json.dump(state, f)
            os.rename(tmp_path, self._state_file_path)
        except Exception as e:
            logger.warn("KernelSoftLockup: Failed to save state: {0}".format(ustr(e)))

    def _get_dmesg_output(self):
        """
        Retrieve dmesg output from the kernel ring buffer.

        Returns:
            str: The dmesg output, or empty string on failure.
        """
        try:
            # run_command() ignores the timeout on Python 2
            # dmesg reads from an in-memory ring buffer, so a hang is not expected.
            return run_command(['dmesg'], track_process=False, timeout=self._DMESG_TIMEOUT)
        except Exception as e:
            logger.warn("KernelSoftLockup: Failed to read dmesg output: {0}".format(ustr(e)))
            return ""

    def _parse_and_aggregate_soft_lockup_events(self, dmesg_output):
        """
        Parse dmesg output for CPU soft lockup events and aggregate them by CPU
        directly into self._event_aggregates. Advances the watermark as it scans.
        """
        found_timestamp = False
        for line in dmesg_output.split('\n'):
            timestamp_match = self._DMESG_TIMESTAMP_PATTERN.match(line)
            if not timestamp_match:
                continue

            found_timestamp = True
            kernel_timestamp = float(timestamp_match.group(1))
            if kernel_timestamp <= self._last_processed_timestamp:
                continue

            self._last_processed_timestamp = kernel_timestamp
            lockup_match = self._SOFT_LOCKUP_PATTERN.search(line)
            if not lockup_match:
                continue

            cpu_id = int(lockup_match.group(1))
            stuck_seconds = int(lockup_match.group(2))

            if cpu_id not in self._event_aggregates:
                self._event_aggregates[cpu_id] = {
                    "count": 0,
                    "max_stuck_seconds": 0,
                    "last_timestamp": kernel_timestamp
                }

            agg = self._event_aggregates[cpu_id]
            agg["count"] += 1
            agg["max_stuck_seconds"] = max(agg["max_stuck_seconds"], stuck_seconds)
            agg["last_timestamp"] = kernel_timestamp

        if not found_timestamp:
            logger.warn(
                "KernelSoftLockup: No kernel timestamps found in dmesg output. "
                "Kernel may have been built without CONFIG_PRINTK_TIME or timestamps are disabled (printk.time=0). "
                "Soft lockup detection will not work without timestamps.")

    def _report_events(self):
        """Report aggregated soft lockup events via telemetry."""
        if not self._event_aggregates:
            return

        try:
            per_cpu = []
            total_events = 0
            for cpu_id, agg in sorted(self._event_aggregates.items()):
                total_events += agg["count"]
                per_cpu.append({
                    "cpuId": cpu_id,
                    "count": agg["count"],
                    "maxStuckTimeSec": agg["max_stuck_seconds"],
                    "lastKernelTimestamp": agg["last_timestamp"]
                })
            affected_cpus = len(per_cpu)
            
            payload = {
                "totalSoftLockups": total_events,
                "affectedCpuCount": affected_cpus,
                "cpuDetails": per_cpu
            }
            message = json.dumps(payload, separators=(',', ':'))

            logger.warn("KernelSoftLockup: {0} soft lockup(s) on {1} CPU(s)".format(
                total_events, affected_cpus))

            add_event(
                AGENT_NAME,
                op=WALAEventOperation.KernelSoftLockup,
                is_success=False,
                message=message,
                log_event=False
            )
        except Exception as e:
            logger.warn("KernelSoftLockup: Failed to send telemetry event: {0}".format(ustr(e)))
        finally:
            self._event_aggregates = {}

    def _operation(self):
        """
        Main operation: parse dmesg, aggregate new soft lockup events, and report.
        Exceptions are caught and logged by the base class (PeriodicOperation.run).
        """
        dmesg_output = self._get_dmesg_output()
        previous_timestamp = self._last_processed_timestamp
        if dmesg_output:
            self._parse_and_aggregate_soft_lockup_events(dmesg_output)
            self._report_events()

        if self._last_processed_timestamp != previous_timestamp:
            self._save_state()
